// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: builtin/logical/pki/lwcrl.proto

package pki

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LWCRLEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotAfter          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	RevocationTimeUtc *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=revocation_time_utc,json=revocationTimeUtc,proto3" json:"revocation_time_utc,omitempty"`
}

func (x *LWCRLEntry) Reset() {
	*x = LWCRLEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_builtin_logical_pki_lwcrl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LWCRLEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LWCRLEntry) ProtoMessage() {}

func (x *LWCRLEntry) ProtoReflect() protoreflect.Message {
	mi := &file_builtin_logical_pki_lwcrl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LWCRLEntry.ProtoReflect.Descriptor instead.
func (*LWCRLEntry) Descriptor() ([]byte, []int) {
	return file_builtin_logical_pki_lwcrl_proto_rawDescGZIP(), []int{0}
}

func (x *LWCRLEntry) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *LWCRLEntry) GetRevocationTimeUtc() *timestamppb.Timestamp {
	if x != nil {
		return x.RevocationTimeUtc
	}
	return nil
}

type LWCRL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Entries map[string]*LWCRLEntry `protobuf:"bytes,10,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *LWCRL) Reset() {
	*x = LWCRL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_builtin_logical_pki_lwcrl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LWCRL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LWCRL) ProtoMessage() {}

func (x *LWCRL) ProtoReflect() protoreflect.Message {
	mi := &file_builtin_logical_pki_lwcrl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LWCRL.ProtoReflect.Descriptor instead.
func (*LWCRL) Descriptor() ([]byte, []int) {
	return file_builtin_logical_pki_lwcrl_proto_rawDescGZIP(), []int{1}
}

func (x *LWCRL) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LWCRL) GetEntries() map[string]*LWCRLEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_builtin_logical_pki_lwcrl_proto protoreflect.FileDescriptor

var file_builtin_logical_pki_lwcrl_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61,
	0x6c, 0x2f, 0x70, 0x6b, 0x69, 0x2f, 0x6c, 0x77, 0x63, 0x72, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x0a, 0x4c, 0x57, 0x43, 0x52, 0x4c, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x37, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x08, 0x6e, 0x6f, 0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x13, 0x72, 0x65,
	0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x74,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x11, 0x72, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x55, 0x74, 0x63, 0x22, 0x99, 0x01, 0x0a, 0x05, 0x4c, 0x57, 0x43, 0x52, 0x4c,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4c, 0x57,
	0x43, 0x52, 0x4c, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x47, 0x0a, 0x0c, 0x45, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4c, 0x57, 0x43,
	0x52, 0x4c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x68, 0x61, 0x73, 0x68, 0x69, 0x63, 0x6f, 0x72, 0x70, 0x2f, 0x76, 0x61, 0x75, 0x6c, 0x74,
	0x2f, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c,
	0x2f, 0x70, 0x6b, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_builtin_logical_pki_lwcrl_proto_rawDescOnce sync.Once
	file_builtin_logical_pki_lwcrl_proto_rawDescData = file_builtin_logical_pki_lwcrl_proto_rawDesc
)

func file_builtin_logical_pki_lwcrl_proto_rawDescGZIP() []byte {
	file_builtin_logical_pki_lwcrl_proto_rawDescOnce.Do(func() {
		file_builtin_logical_pki_lwcrl_proto_rawDescData = protoimpl.X.CompressGZIP(file_builtin_logical_pki_lwcrl_proto_rawDescData)
	})
	return file_builtin_logical_pki_lwcrl_proto_rawDescData
}

var file_builtin_logical_pki_lwcrl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_builtin_logical_pki_lwcrl_proto_goTypes = []interface{}{
	(*LWCRLEntry)(nil),            // 0: LWCRLEntry
	(*LWCRL)(nil),                 // 1: LWCRL
	nil,                           // 2: LWCRL.EntriesEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_builtin_logical_pki_lwcrl_proto_depIdxs = []int32{
	3, // 0: LWCRLEntry.not_after:type_name -> google.protobuf.Timestamp
	3, // 1: LWCRLEntry.revocation_time_utc:type_name -> google.protobuf.Timestamp
	2, // 2: LWCRL.entries:type_name -> LWCRL.EntriesEntry
	0, // 3: LWCRL.EntriesEntry.value:type_name -> LWCRLEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_builtin_logical_pki_lwcrl_proto_init() }
func file_builtin_logical_pki_lwcrl_proto_init() {
	if File_builtin_logical_pki_lwcrl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_builtin_logical_pki_lwcrl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LWCRLEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_builtin_logical_pki_lwcrl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LWCRL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_builtin_logical_pki_lwcrl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_builtin_logical_pki_lwcrl_proto_goTypes,
		DependencyIndexes: file_builtin_logical_pki_lwcrl_proto_depIdxs,
		MessageInfos:      file_builtin_logical_pki_lwcrl_proto_msgTypes,
	}.Build()
	File_builtin_logical_pki_lwcrl_proto = out.File
	file_builtin_logical_pki_lwcrl_proto_rawDesc = nil
	file_builtin_logical_pki_lwcrl_proto_goTypes = nil
	file_builtin_logical_pki_lwcrl_proto_depIdxs = nil
}
